apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-postgres-pvc
  namespace: odoo
  labels:
    app: odoo-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi